---
output: html_document
editor_options: 
  chunk_output_type: console
---

Load packages and functions. Some packages need to be loaded in this order, or they will clash with other packages. So, keep this order.  
```{r message=FALSE, warning=FALSE, include=FALSE, results='hide'}
setwd("C:/Users/Loay Jabre/Desktop/PhD/Data/FragTranscriptome/Transcriptome")

library(ggplot2)
library(plyr)
library(dplyr)
library(gplots)
library(RColorBrewer)
library(reshape2)
library(tidyr)
library(plotly)
library(gsubfn)
library(ggrepel)
library(gridExtra)
library(htmlwidgets)
library(VennDiagram)
```
 

 
cell counts 
```{r}
cellcounts <- read.csv ("cellcounts.csv")
cellcounts_sub <- cellcounts [, cellcounts [1, ] == "1000"]
cellcounts_sub$type <- cellcounts$X


cellcounts_sub <- cellcounts_sub [-c(1),]
cellcounts_sub1 <- cellcounts_sub [c(1:3, 37)]
cellcounts_sub2 <- melt(data = cellcounts_sub1, id.vars  = "type")

ggplot (cellcounts_sub2, aes(y = value, x=reorder(type,value)))+
  geom_point()+
  scale_y_log10()+
  #geom_boxplot()+
  theme_bw()+
  ylab("cells / mL")+
  theme(axis.title.x = element_text (size = 15, face="bold"))+
  theme(axis.title.y = element_text (size = 15, face="bold"))+
  xlab("taxa")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))



pseudo_frag_cellcount <- dplyr::filter(cellcounts_sub, grepl('Pseudo-nitzschia total|Frag', type))

pseudo_frag_cellcount <- pseudo_frag_cellcount [c(37, 1:6, 10:15, 19:24, 28:30)]

names(pseudo_frag_cellcount) <- c("taxa","A_initial_initial", "B_initial_initial", "C_initial_initial", "A_noFe_0", "B_noFe_0", "C_noFe_0", "A_Fe_0", "B_Fe_0", "C_Fe_0", "A_noFe_3", "B_noFe_3", "C_noFe_3", "A_Fe_3", "B_Fe_3", "C_Fe_3","A_noFe_6", "B_noFe_6", "C_noFe_6", "A_Fe_6", "B_Fe_6", "C_Fe_6")


pseudo_frag_cellcount_subss <- pseudo_frag_cellcount [-c(2:4)]

pseudo_frag_cellcount_sub <-  melt (data = pseudo_frag_cellcount_subss,id.vars = "taxa")
  
pseudo_frag_cellcount_sub <- separate(pseudo_frag_cellcount_sub, col = variable, into = c("Rep", "Fe", "temperature"))





frag_cellcount <- dplyr::filter(cellcounts_sub, grepl('Frag', type))

frag_cellcount <- frag_cellcount [c(37, 1:6, 10:15, 19:24, 28:30)]

names(frag_cellcount) <- c("taxa","A_initial_initial", "B_initial_initial", "C_initial_initial", "A_noFe_0", "B_noFe_0", "C_noFe_0", "A_Fe_0", "B_Fe_0", "C_Fe_0", "A_noFe_3", "B_noFe_3", "C_noFe_3", "A_Fe_3", "B_Fe_3", "C_Fe_3","A_noFe_6", "B_noFe_6", "C_noFe_6", "A_Fe_6", "B_Fe_6", "C_Fe_6")

frag_cellcount_sub <-  melt (data =frag_cellcount,id.vars = "taxa")
  
frag_cellcount_sub <- separate(frag_cellcount_sub, col = variable, into = c("Rep", "Fe", "temperature"))



pseudo_frag_cellcount_sub %>% group_by(temperature, Fe, taxa) %>%
  summarise(
    count = n(),
    mean = mean(value, na.rm = TRUE),
    sd = sd(value, na.rm = TRUE)
  )



#plot

x<- ggplot(pseudo_frag_cellcount_sub, aes(x=temperature,
                      y=value, 
                      color = Fe))+
  geom_point(size = 3, alpha = 0.3)+
 # geom_point(size = 2, shape = 1, color = "black")+
  xlab ("Temperature (°C)")+
  ylab ("Cell count (mL-1)")+
  theme_bw()+
  scale_x_discrete(limits=c("0","3","6"))+
  #scale_x_discrete(limits=c("initial","0","3","6"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(axis.text.x = element_text( vjust = 1.0, hjust = 1.0))+
 # guides(fill=guide_legend("my awesome title"))+
  # scale_color_manual (breaks = c("Initial", "Fe", "noFe"),
  #                      values = c("red", "gray", "black"))+
  scale_color_manual (breaks = c("Fe", "noFe"),
                       values = c("red", "black"))+
 # scale_shape_manual (breaks = c("Initial", "Fe", "noFe"),
                      # values = c(21, 21, 20))+
  labs (color = "")+
  facet_wrap(~taxa)+
  stat_summary(fun.y = mean, geom = "point", aes(color = Fe), size = 4)+
  #stat_summary(fun.data = mean_se, geom = "errorbar",aes(color = Fe) , width =0.1)+
  stat_summary(fun.data = mean_cl_boot , geom = "errorbar",aes(color = Fe) , width =0.1)+
    theme(axis.text.x=element_text(face = "bold", size = 12),
        axis.title.x=element_text(size=13,face="bold"), 
        axis.text.y=element_text(face = "bold", size = 12),
        axis.title.y=element_text(size=13,face="bold"))+
  theme(legend.position = c(0.05,0.92))
          
#scale_shape_manual(values = c(16, 3,1))+
       #scale_y_log10()
ggplotly(x)





```


Stats
```{r}

str(frag_cellcount_sub)


model <- lm(value~temperature*Fe,data=frag_cellcount_sub  )

anova(model)
plot(model,2)

#assumption 1: normal distribution. 
aov_residuals <- residuals(object = model)
shapiro.test(aov_residuals)
#you want the value to be higher than 0.05 here

#assumption 2 : Homogeneity of variance 
plot(model,1)


x <- aov (value~taxa, data=pseudo_frag_cellcount_sub)
summary(x)

TukeyHSD(x)

#https://www.youtube.com/watch?v=yhHvzlJYqQY
```

